#!/bin/bash


source 	./conditions
while true;
do

read -p "Enter your DB Name: " DB_name

if [ -e "$HOME/db/$DB_name" ];then

	echo "DB already exists"
	continue

elif CheckIfValid $DB_name ; then
	mkdir $HOME/db/$DB_name
	echo "Added successfully"
	ls $HOME/db
	break

else 
	echo "Invalid input please try again"
	continue
fi
done
