#!/bin/bash

source  ./conditions

while true; do
    echo "name of the DB:"
    read db_name

    if CheckIfValid $db_name; then
        path=~/db/$db_name
        if [ -e $path ]; then

            echo "sure you want to delete $db_name? "
            read opt
            case $opt in
                "y" )
                    rm -rf $path
                    echo "dropped"
                    break 2
                    ;;

                "n")
                    echo "Your DB is safe"
                    break 2
                    ;;
                *)
                    echo "please enter an input again"
                    ;;
            esac

        else
            echo "DB not found!"
        fi

    else
        echo "invalid!"
        continue
    fi
done

