#!/bin/bash

path=~/db

for ele in $(ls -l $path)
do
	echo $ele
done

echo "which DB you want?"
read opt

if CheckIfValid $db_name ;then
    path_2=$path/$opt

elif [ -d $path_2 ]; then
    for tb in $(ls -1 $path_2)
    do
        echo $tb

    done
else
    echo "DB not found!"
fi

#read what inside the table 

#table_path="$path_2/$table_name"

