#!/bin/bash

if [ -d "$HOME/db" ]; then
    echo "Welcome How can I assist you?"
    cd "$HOME/MDY_DB/BD_funcs"  
    PS3='Enter your choice: '
    options=("create new DB" "list DB" "connect to DB" "drop DB")
    select opt in "${options[@]}"
    do
        case $opt in
            "create new DB")
                echo "Creating new DB..."
                . create_DB  
                break
                ;;

            "list DB")
                echo "Listing DB..."
                . "$HOME/MDY_DB/BD_funcs/listInfo_DB"  
                break
                ;;

            "connect to DB")
                echo "Connecting to DB..."
                . "$HOME/MDY_DB/BD_funcs/connectTo_DB"  
                break
                ;;

            "drop DB")
                echo "Dropping DB..."
                . "$HOME/MDY_DB/BD_funcs/dropFrom_DB"  
                break
                ;;

            *) 
                echo "Invalid option $REPLY";;
        esac
    done
else
    mkdir "$HOME/db"
    echo "Ready!"
fi

